version: "3"
services:
   api:
     stdin_open: true
     tty: true
     build: .
     image: devops-test2
     container_name:  api.easy-rolls-royce.com
     restart: always
     volumes:
       - /docker/deploy/api.easy-rolls-royce.com:/deploy/app/api.easy-rolls-royce.com
       - /docker/deploy/api.easy-rolls-royce.com/logs:/deploy/app/api.easy-rolls-royce.com/logs/
       - /docker/deploy/api.easy-rolls-royce.com/gunicorn_log:/deploy/app/api.easy-rolls-royce.com/gunicorn_log
     ports:
       - "5200:5200"
     command:
       - /bin/bash
       - -c
       - |
          cd api.easy-rolls-royce.com
          python3 gunicorn.py start
          /bin/bash